# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Andrew Leedham
email: AndrewLeedham@Outlook.com
description: >
  Andrew Leedham's Portfolio - Web Design, Game Dev and Photography.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://AndrewLeedham.github.io/" # the base hostname & protocol for your site

#Social
tumblr_username: andrew-leedham
github_username:  AndrewLeedham

# Build settings
markdown: kramdown
