# Site settings
title: Andrew Leedham's Portfolio
email: AndrewLeedham@Outlook.com
description: Andrew Leedham’s Portfolio. Web Design, Web Developement, Game Development, Photography and much more...
baseurl: ""
url: "http://AndrewLeedham.github.io"

#Image settings
imagepath: "/img"
jspath: "/js"

# Social
github:  https://github.com/AndrewLeedham
instagram: https://instagram.com/andrew_leedham/
stackoverflow: http://stackoverflow.com/users/2386508/andrew-leedham
linkedin: https://linkedin.com/in/andrew-leedham-ba864b112/

# Build settings
markdown: kramdown
highlighter: rouge
exclude: [Gemfile, Gemfile.lock, Guardfile, todo.md, safe.storage]
empty: []
# jekyll-archives:
#   enabled: all
#   layout: 'archive'
#   permalinks:
#     year: '/archive/:year/'
#     month: '/archive/:year/:month/'
#     category: '/archive/category/:name/'
# gems:
#   - jekyll-archives
