# Site settings
title: Andrew Leedham's Portfolio
email: AndrewLeedham@Outlook.com
description: Andrew Leedham’s Portfolio. Web Design, Web Developement, Game Development, Photography and much more...
baseurl: ""
url: "http://AndrewLeedham.github.io"

#Image settings
imagepath: "/img"
jspath: "/js"

# Social
twitter: "AndrewJLeedham"
github:  "AndrewLeedham"
tumblr: "andrew-leedham"
twitch: "Formulayeti"
youtube: "HowNot2Play"

# Collections
collections:
- projects

# Build settings
markdown: kramdown
highlighter: rouge
exclude: [todo.md, safe.storage, package.json, node_modules, GulpFile.js]
empty: []